project_dict = {
    "SCAN English": {
        "project_id": "22461",
        "Report Id": "65971",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location"
    },
    "SCAN Spanish": {
        "project_id": "22475",
        "Report Id": "89778",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location"
    },
    "SCAN Russian": {
        "project_id": "22472",
        "Report Id": "89753",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location"
    },
    "SCAN Vietnamese": {
        "project_id": "22477",
        "Report Id": "89783",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location"
    },
    "SCAN Trad Chinese": {
        "project_id": "22474",
        "Report Id": "89761",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location"
    },
    "HCT": {
        "project_id": "45",
        "Report Id": "10",
        "project_type": "longitudinal",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "time_test_order": "Order Date",
        "Order Date Format": "%Y-%m-%d %H:%M:%S",
        "core_participant_first_name": "First Name",
        "core_participant_last_name": "Last Name",
        "core_home_street": "Street Address",
        "core_apartment_number": "Apt Number",
        "core_home_city": "City",
        "core_home_state": "State",
        "core_zipcode": "Zipcode",
        "core_home_street_2": "Street Address 2",
        "core_apartment_number_2": "Apt Number 2",
        "core_home_city_2": "City 2",
        "core_home_state_2": "State 2",
        "core_zipcode_2": "Zipcode 2",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location"
    },
    "Cascadia": {
        "project_id": "46238",
        "Report Id": "144242",
        "project_type": "longitudinal",
        "ptid": "Record Id",
        "household_id": "Household ID",
        "ss_date_2": "Order Date",
        "ss_pickup_1": "Pickup 1",
        "ss_pickup_2": "Pickup 2",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "es_street_address": "Street Address",
        "es_apt_num": "Apt Number",
        "es_city": "City",
        "es_state": "State",
        "es_zipcode": "Zipcode",
        "es_dropoff_location": "Delivery Instructions",
        "ss_street_address": "Street Address 2",
        "ss_apt_num": "Apt Number 2",
        "ss_city": "City 2",
        "ss_state": "State 2",
        "ss_zipcode": "Zipcode 2",
        "participant_email": "Email",
        "participant_phone": "Phone",
        "ss_pu_location": "Pickup Location"
    },
    "AIRS": {
        "project_id": "1372",
        "Report Id": "14107",
        "subject_id": "Record Id",
        "project_type": "longitudinal",
        "enr_email": "Email",
        "scr_phone": "Phone",
        "Order Date Format": "%d-%m-%Y",
        "scr_first_name": "First Name",
        "scr_last_name": "Last Name",
        "enr_mail_street_address": "Street Address",
        "enr_mail_street_address_2": "Apt Number",
        "enr_mail_city": "City",
        "enr_mail_state": "State",
        "enr_mail_zip": "Zipcode",
        "wk_date": "Order Date",
        "wk_tod_tom_calc": "Today Tomorrow",
        "wk_street_address": "Street Address 2",
        "wk_street_addrewk_2": "Apt Number 2",
        "wk_city": "City 2",
        "wk_state": "State 2",
        "wk_mail_zip": "Zipcode 2",
        "wk_del_instr": "Delivery Instructions",
        "wk_ret_kit_where": "Pickup Location",
        "ss_date": "Order Date 2",
        "ss_tod_tom_calc": "Today Tomorrow 2",
        "ss_street_address": "Street Address 3",
        "ss_street_address_2": "Apt Number 3",
        "ss_city": "City 3",
        "ss_state": "State 3",
        "ss_mail_zip": "Zipcode 3",
        "ss_del_instr": "Delivery Instructions 2",
        "ss_ret_kit_where": "Pickup Location 2"
    }
}