project_dict = {
    "SCAN English": {
        "project_id": "22461",
        "Report Id": "65971",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location",
        "pre_scan_barcode": "Collection",
        "back_end_scan": "BEMS",
    },
    "SCAN Spanish": {
        "project_id": "22475",
        "Report Id": "89778",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location",
        "pre_scan_barcode": "Collection",
        "back_end_scan": "BEMS",
    },
    "SCAN Vietnamese": {
        "project_id": "22477",
        "Report Id": "89783",
        "project_type": "cross-sectional",
        "record_id": "Record Id",
        "tod_tom_calc": "Today Tomorrow",
        "illness_q_date_time": "Order Date",
        "participant_first_name": "First Name",
        "participant_last_name": "Last Name",
        "home_street": "Street Address",
        "apartment_number": "Apt Number",
        "homecity_other": "City",
        "home_state": "State",
        "home_zipcode_2": "Zipcode",
        "special_instructions": "Delivery Instructions",
        "email": "Email",
        "phone_number": "Phone",
        "text_or_email": "Notification Pref",
        "return_special_instruct": "Pickup Location",
        "pre_scan_barcode": "Collection",
        "back_end_scan": "BEMS",
    }
}
