#!/usr/bin/env bash

PGSERVICE=seattleflu-production psql -c "\copy (
    with q as (select sample_id, pa.details ->> 'device' as device, info.\"geneTarget\", array_agg(crt) as crt_vals, present
from warehouse.presence_absence as pa,
jsonb_to_recordset(pa.details -> 'replicates') as info(\"geneTarget\" text, crt text)
where info.\"geneTarget\" in ('COVID-19_Orf1b', 'COVID-19_S_gene', 'COVID-19-S_gene', 'SARS-CoV-2_Orf1b', 'SARS-CoV-2_S')
and pa.details ->> 'device' = 'TaqmanQPCR'
and sample_id is not null
and (present or present is null)
group by sample_id, info.\"geneTarget\", present, pa.details ->> 'device'),

crt as (select distinct on (sample_id) sample_id, device, present,
    MAX(case when \"geneTarget\" = 'COVID-19-S_gene' or \"geneTarget\" = 'COVID-19_S_gene' or \"geneTarget\" = 'SARS-CoV-2_S' then crt_vals[1] end) as S_gene_crt_1,
    MAX(case when \"geneTarget\" = 'COVID-19-S_gene' or \"geneTarget\" = 'COVID-19_S_gene' or \"geneTarget\" = 'SARS-CoV-2_S' then crt_vals[2] end) as S_gene_crt_2,
    MAX(case when \"geneTarget\" = 'COVID-19_Orf1b' or \"geneTarget\" = 'SARS-CoV-2_Orf1b' then crt_vals[1] end) as Orf1b_crt_1,
    MAX(case when \"geneTarget\" = 'COVID-19_Orf1b' or \"geneTarget\" = 'SARS-CoV-2_Orf1b' then crt_vals[2] end) as Orf1b_crt_2
from q
where array_length(crt_vals, 1) = 2
group by sample_id, device, present
order by sample_id, device)

Select
    encounter_id,
    sample_id,
    case
        when scan_study_arm = 'priority_arm_1' OR priority_code is not null
            then 'Priority Code'
        when scan_study_arm = 'group_enroll_arm_4'
            then 'Group Enrollment'
        when scan_study_arm = 'asymptomatic_arm_3' OR scan_study_arm = 'symptomatic_arm_2'
            then 'Community Enrollment'
    end as enrollment_method,
    case
        when substring(puma,3,5) IN ('11610', '11611', '11612', '11613', '11614', '11615')
            then 'South King County'
        when substring(puma,3,5) IN ('11601', '11602', '11603', '11604', '11605', '11606', '11607', '11608', '11609', '11616')
            then 'North King County'
        when substring(puma,3,3) = '115' 
            then 'Pierce County'
        when substring(puma,3,3) = '117' 
            then 'Snohomish County'
        when substring(puma,3,3) = '109'
            then 'Yakima County'
    END as region,
    SE.encountered::date,
    SE.sex,
    SE.age,
        case
		when hispanic_or_latino
			then 'Hispanic or Latino, any Race'
		when race @> '{"other"}' or array_length(race, 1) > 1
			then 'Other/Multi, Non Hisp.'
		when race @> '{"white"}'
			then 'White, not Hispanic'
		when race @> '{"americanIndianOrAlaskaNative"}'
			then 'Amer. Indian or Alaska Native'
		when race @> '{"blackOrAfricanAmerican"}'
			then 'Black, not Hispanic'
		when race @> '{"asian"}'
			then 'Asian, not Hispanic'
		when race @> '{"nativeHawaiian"}'
			then 'NH/OPI'
	end as race_ethnicity,
    case 
        when PA.present is null and sample_id is null
            then 'Not Tested'
        when PA.present is null and sample_id is not null
            then 'Pending'
        else PA.present
    end as hcov19_result,
    SE.prior_test_positive,
    SE.covid_vax,
    SE.vaccine_manufacturer,
    SE.number_of_covid_doses,
    greatest(V.calculated_vac_date_1, V.calculated_vac_date_2, V.calculated_vac_date_3) as date_last_covid_dose,
    V.calculated_covid_doses as covid_doses,
    V.best_available_vac_status as vaccination_status,
    V.calculated_vac_date_1 as vac_date_1,
    V.calculated_vac_date_2 as vac_date_2,
    V.calculated_vac_date_3 as vac_date_3,
    V.calculated_vac_name_1 as vac_name_1,
    V.calculated_vac_name_2 as vac_name_2,
    V.calculated_vac_name_3 as vac_name_3,
    crt.*
From
    shipping.scan_encounters_v1 as SE
    left join shipping.scan_encounters_with_best_available_vaccination_data_v1 V using (encounter_id)
    left join (
        select PA.sample_id,
            case
                when present then 'Positive'
                when not present then 'Negetive'
                when present is null then 'Inconclusive'
            end as present
        from shipping.hcov19_presence_absence_result_v1 PA
        ) PA using (sample_id)
    left join crt using (sample_id)
order by
    encountered desc
)
to ./data/id3c_scan_vaccine_data.csv csv header;"
